"""
IPL Cricket Analysis — Streamlit App
======================================
Run with:  streamlit run app.py

This single file does everything: loads data, computes stats, and renders
the whole dashboard. It's organized top-to-bottom in the same order it
displays on the page, so it's easy to walk through when explaining it:

  1. Page setup
  2. Load data (cached so it's fast after the first run)
  3. Sidebar controls (the settings a viewer can change)
  4. Best Batsmen section
  5. Best Bowlers section
  6. Winning Teams section
  7. Toss Impact section
"""

import os
import pandas as pd
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import plotly.express as px

# ----------------------------------------------------------------------------
# 1. PAGE SETUP
# ----------------------------------------------------------------------------
st.set_page_config(page_title="IPL Cricket Analysis", page_icon="🏏", layout="wide")

BASE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE, "data")

st.title("🏏 IPL Cricket Analysis")
st.caption(
    "Best batsmen, best bowlers, winning teams, and whether the toss actually matters. "
    "Adjust the settings on the left and everything below updates automatically."
)

# ----------------------------------------------------------------------------
# 2. LOAD DATA
# ----------------------------------------------------------------------------
# @st.cache_data means this only actually re-reads the CSVs when the files
# change — makes the app feel instant after the first load.

@st.cache_data
def load_data():
    matches = pd.read_csv(os.path.join(DATA_DIR, "matches.csv"))
    batting = pd.read_csv(os.path.join(DATA_DIR, "batting_innings.csv"))
    bowling = pd.read_csv(os.path.join(DATA_DIR, "bowling_innings.csv"))
    return matches, batting, bowling

# If no data exists yet, generate the sample dataset automatically.
if not os.path.exists(os.path.join(DATA_DIR, "matches.csv")):
    with st.spinner("First run — generating sample IPL data..."):
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "generate_data", os.path.join(DATA_DIR, "generate_data.py"))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)

matches, batting, bowling = load_data()

with st.expander("ℹ️ About this data"):
    st.write(
        "This uses a **synthetic but realistic** IPL dataset (10 teams, 2018–2024, "
        f"{matches['match_id'].nunique()} matches) generated by `data/generate_data.py`, "
        "since no live dataset was pulled in. To use real data, replace the three CSVs "
        "in the `data/` folder with your own (same column names) and restart the app."
    )

# ----------------------------------------------------------------------------
# 3. SIDEBAR CONTROLS
# ----------------------------------------------------------------------------
st.sidebar.header("⚙️ Settings")

st.sidebar.subheader("Batsmen")
top_n_bat = st.sidebar.slider("How many batsmen to show", 3, 30, 10)
bat_rank_by = st.sidebar.selectbox(
    "Rank batsmen by", ["runs", "average", "strike_rate", "hundreds"],
    format_func=lambda x: {"runs": "Total runs", "average": "Batting average",
                            "strike_rate": "Strike rate", "hundreds": "Most hundreds"}[x]
)
min_innings = st.sidebar.slider("Minimum innings to qualify", 1, 50, 15)

st.sidebar.subheader("Bowlers")
top_n_bowl = st.sidebar.slider("How many bowlers to show", 3, 30, 10)
bowl_rank_by = st.sidebar.selectbox(
    "Rank bowlers by", ["wickets", "economy", "average"],
    format_func=lambda x: {"wickets": "Most wickets", "economy": "Best economy",
                            "average": "Best bowling average"}[x]
)
min_overs = st.sidebar.slider("Minimum overs to qualify", 1, 80, 20)

# ----------------------------------------------------------------------------
# COMPUTE: BATSMEN
# ----------------------------------------------------------------------------
bat_agg = batting.groupby("player").agg(
    innings=("match_id", "count"), runs=("runs", "sum"), balls=("balls", "sum"),
    fours=("fours", "sum"), sixes=("sixes", "sum"), dismissals=("out", "sum"),
).reset_index()
bat_agg["average"] = (bat_agg["runs"] / bat_agg["dismissals"].replace(0, np.nan)).round(2)
bat_agg["strike_rate"] = (bat_agg["runs"] / bat_agg["balls"] * 100).round(2)

per_innings = batting.copy()
per_innings["is_50"] = (per_innings["runs"] >= 50) & (per_innings["runs"] < 100)
per_innings["is_100"] = per_innings["runs"] >= 100
fh = per_innings.groupby("player").agg(fifties=("is_50", "sum"), hundreds=("is_100", "sum")).reset_index()
bat_agg = bat_agg.merge(fh, on="player", how="left")

qualified_bat = bat_agg[bat_agg["innings"] >= min_innings].copy()
top_batsmen = qualified_bat.sort_values(bat_rank_by, ascending=False).head(top_n_bat)

# ----------------------------------------------------------------------------
# COMPUTE: BOWLERS
# ----------------------------------------------------------------------------
bowl_agg = bowling.groupby("player").agg(
    innings=("match_id", "count"), overs=("overs", "sum"),
    runs_conceded=("runs_conceded", "sum"), wickets=("wickets", "sum"),
).reset_index()
bowl_agg["economy"] = (bowl_agg["runs_conceded"] / bowl_agg["overs"]).round(2)
bowl_agg["average"] = (bowl_agg["runs_conceded"] / bowl_agg["wickets"].replace(0, np.nan)).round(2)

qualified_bowl = bowl_agg[bowl_agg["overs"] >= min_overs].copy()
bowl_ascending = bowl_rank_by in ("economy", "average")  # lower is better for these
top_bowlers = qualified_bowl.sort_values(bowl_rank_by, ascending=bowl_ascending).head(top_n_bowl)

# ----------------------------------------------------------------------------
# COMPUTE: TEAMS
# ----------------------------------------------------------------------------
total_matches_per_team = pd.concat([matches["team1"], matches["team2"]]).value_counts()
wins_per_team = matches["winner"].value_counts()
team_summary = pd.DataFrame({"matches_played": total_matches_per_team, "wins": wins_per_team}).fillna(0)
team_summary["wins"] = team_summary["wins"].astype(int)
team_summary["win_pct"] = (team_summary["wins"] / team_summary["matches_played"] * 100).round(2)
team_summary = team_summary.sort_values("wins", ascending=False).reset_index().rename(columns={"index": "team"})

# ----------------------------------------------------------------------------
# COMPUTE: TOSS IMPACT
# ----------------------------------------------------------------------------
matches["toss_won_match"] = matches["toss_winner"] == matches["winner"]
overall_toss_win_pct = round(matches["toss_won_match"].mean() * 100, 2)
toss_by_decision = (
    matches.groupby("toss_decision")["toss_won_match"]
    .mean().mul(100).round(2).reset_index()
    .rename(columns={"toss_won_match": "win_pct"})
)
toss_by_season = matches.groupby("season")["toss_won_match"].mean().mul(100).round(2).reset_index()

# ----------------------------------------------------------------------------
# 4. BEST BATSMEN
# ----------------------------------------------------------------------------
st.header("🏏 Best Batsmen")
col1, col2 = st.columns([1, 1])

with col1:
    fig, ax = plt.subplots(figsize=(7, 5))
    d = top_batsmen.sort_values(bat_rank_by)
    ax.barh(d["player"], d[bat_rank_by], color="#004BA0")
    ax.set_xlabel(bat_rank_by.replace("_", " ").title())
    ax.set_title(f"Top {top_n_bat} by {bat_rank_by.replace('_',' ').title()} (Matplotlib)")
    st.pyplot(fig)

with col2:
    fig = px.scatter(
        top_batsmen, x="strike_rate", y="runs", text="player",
        size=(top_batsmen["fours"] + top_batsmen["sixes"]).clip(lower=1),
        color="average", color_continuous_scale="Blues",
        title="Runs vs Strike Rate (bubble = boundaries) — Plotly",
        labels={"strike_rate": "Strike Rate", "runs": "Total Runs"}
    )
    fig.update_traces(textposition="top center")
    st.plotly_chart(fig, use_container_width=True)

st.dataframe(
    top_batsmen[["player", "innings", "runs", "average", "strike_rate", "fifties", "hundreds"]]
    .reset_index(drop=True),
    use_container_width=True
)

# ----------------------------------------------------------------------------
# 5. BEST BOWLERS
# ----------------------------------------------------------------------------
st.header("🎯 Best Bowlers")
col1, col2 = st.columns([1, 1])

with col1:
    fig, ax = plt.subplots(figsize=(7, 5))
    d = top_bowlers.sort_values(bowl_rank_by, ascending=not bowl_ascending)
    ax.barh(d["player"], d[bowl_rank_by], color="#D71920")
    ax.set_xlabel(bowl_rank_by.replace("_", " ").title())
    ax.set_title(f"Top {top_n_bowl} by {bowl_rank_by.replace('_',' ').title()} (Matplotlib)")
    st.pyplot(fig)

with col2:
    fig = px.scatter(
        top_bowlers, x="economy", y="wickets", text="player",
        size="overs", color="wickets", color_continuous_scale="Reds",
        title="Wickets vs Economy (bubble = overs bowled) — Plotly",
        labels={"economy": "Economy Rate", "wickets": "Total Wickets"}
    )
    fig.update_traces(textposition="top center")
    st.plotly_chart(fig, use_container_width=True)

st.dataframe(
    top_bowlers[["player", "innings", "overs", "wickets", "economy", "average"]]
    .reset_index(drop=True),
    use_container_width=True
)

# ----------------------------------------------------------------------------
# 6. WINNING TEAMS
# ----------------------------------------------------------------------------
st.header("🏆 Winning Teams")
col1, col2 = st.columns([1, 1])

with col1:
    fig, ax = plt.subplots(figsize=(7, 5))
    d = team_summary.sort_values("wins")
    ax.barh(d["team"], d["wins"], color="#F5A623")
    ax.set_xlabel("Wins")
    ax.set_title("Total Wins by Team (Matplotlib)")
    st.pyplot(fig)

with col2:
    fig = px.bar(
        team_summary.sort_values("wins"), x="wins", y="team", orientation="h",
        color="win_pct", color_continuous_scale="Viridis",
        title="Team Wins & Win % — Plotly",
        labels={"wins": "Total Wins", "team": "Team", "win_pct": "Win %"}
    )
    st.plotly_chart(fig, use_container_width=True)

st.dataframe(team_summary.reset_index(drop=True), use_container_width=True)

# ----------------------------------------------------------------------------
# 7. TOSS IMPACT
# ----------------------------------------------------------------------------
st.header("🪙 Toss Impact")

decision_text = ", ".join(
    f"{row.win_pct}% when choosing to {row.toss_decision} first"
    for row in toss_by_decision.itertuples()
)
st.info(
    f"The team that wins the toss goes on to win the match "
    f"**{overall_toss_win_pct}%** of the time ({decision_text})."
)

col1, col2 = st.columns([1, 1])

with col1:
    fig, axes = plt.subplots(1, 2, figsize=(8, 4.5))
    axes[0].bar(["Toss winner\nwon match", "Toss winner\nlost match"],
                [overall_toss_win_pct, 100 - overall_toss_win_pct], color=["#2E7D32", "#C62828"])
    axes[0].set_ylim(0, 100)
    axes[0].set_title("Does the Toss Help?")
    axes[1].bar(toss_by_decision["toss_decision"], toss_by_decision["win_pct"], color=["#1565C0", "#EF6C00"])
    axes[1].set_ylim(0, 100)
    axes[1].set_title("By Toss Decision")
    fig.suptitle("Matplotlib")
    plt.tight_layout()
    st.pyplot(fig)

with col2:
    fig = px.line(
        toss_by_season, x="season", y="toss_won_match", markers=True,
        title="Toss Winner's Win % by Season — Plotly",
        labels={"season": "Season", "toss_won_match": "Win % when winning the toss"}
    )
    fig.add_hline(y=50, line_dash="dash", line_color="gray")
    fig.update_yaxes(range=[0, 100])
    st.plotly_chart(fig, use_container_width=True)
